// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABOzvTZ7K0oVlpsI-l7iRxA7hYD699ZC4',
    appId: '1:757970324966:web:cdc10e2a8fc1448b839a27',
    messagingSenderId: '757970324966',
    projectId: 'flutterproweb',
    authDomain: 'flutterproweb.firebaseapp.com',
    storageBucket: 'flutterproweb.firebasestorage.app',
    measurementId: 'G-7MY2DWBS2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnM_6edisxLA3HftWlDMO7CBH-C1BOPb8',
    appId: '1:757970324966:android:65493ff075318755839a27',
    messagingSenderId: '757970324966',
    projectId: 'flutterproweb',
    storageBucket: 'flutterproweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMYrme9kJ5Zlb9eMF414FUegrjlRfJDfc',
    appId: '1:757970324966:ios:01311d0537e76180839a27',
    messagingSenderId: '757970324966',
    projectId: 'flutterproweb',
    storageBucket: 'flutterproweb.firebasestorage.app',
    iosBundleId: 'com.example.webprofile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMYrme9kJ5Zlb9eMF414FUegrjlRfJDfc',
    appId: '1:757970324966:ios:01311d0537e76180839a27',
    messagingSenderId: '757970324966',
    projectId: 'flutterproweb',
    storageBucket: 'flutterproweb.firebasestorage.app',
    iosBundleId: 'com.example.webprofile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABOzvTZ7K0oVlpsI-l7iRxA7hYD699ZC4',
    appId: '1:757970324966:web:0be4dc85c7a5f7e1839a27',
    messagingSenderId: '757970324966',
    projectId: 'flutterproweb',
    authDomain: 'flutterproweb.firebaseapp.com',
    storageBucket: 'flutterproweb.firebasestorage.app',
    measurementId: 'G-HBYWP1VFG4',
  );

}